{% set name = "bugsnag" %}
{% set version = "4.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98408fe17d4a7f300a56535407a6448b9844d9b528c44527908868fc3646e873

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - webob

test:
  requires:
    - python {{ python_min }}
  imports:
    - bugsnag

about:
  home: https://bugsnag.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Automatic error monitoring for django, flask, etc.
  dev_url: https://github.com/bugsnag/bugsnag-python

extra:
  recipe-maintainers:
    - tschoonj
