{% set name = "bugsnag" %}
{% set version = "4.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33933c82ace14a51921e0b5f6796725bc0445ce99e2015b63312fda4bb4d9ec2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - webob

test:
  requires:
    - python {{ python_min }}
  imports:
    - bugsnag

about:
  home: https://bugsnag.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Automatic error monitoring for django, flask, etc.
  dev_url: https://github.com/bugsnag/bugsnag-python

extra:
  recipe-maintainers:
    - tschoonj
